#ifndef _AVRTOS_SYSCLOCK_CONFIG
#define _AVRTOS_SYSCLOCK_CONFIG

/*___________________________________________________________________________*/

#include <avr/io.h>

#include "defines.h"

/*___________________________________________________________________________*/

// TODO :  
//  - automatically calculate timer parameter in preprocessor for an 
//      input time slice
//  - make it compatible with 8MHz clock

// NOTE : 
//  - as thread context switch is 26µs and it is not advice to do context 
//      switch more than 10% of the time.
//
//  - maximum time slice must be 26µs*9 = 234µs ~ 4273 Hz
//
//  - If using Arduino Framework, as timer0 is used by the `millis()` function:
//      Timer1 or 2 should be used for the syslock timer.
//      https://github.com/arduino/ArduinoCore-avr/blob/master/cores/arduino/wiring.c#L65-L77
//      
//  - If using qemu for avr, only timer1 is supported at the time :
//      https://qemu-project.gitlab.io/qemu/system/target-avr.html
//      https://github.com/qemu/qemu/blob/master/hw/timer/avr_timer16.c

/*___________________________________________________________________________*/

// registers

#if KERNEL_SYSLOCK_HW_TIMER == 0

#define SYSCLOCK_HW_REG_CSX0    CS00
#define SYSCLOCK_HW_REG_CSX1    CS01
#define SYSCLOCK_HW_REG_CSX2    CS02

#define SYSCLOCK_HW_REG_TCCRXA  TCCR0A
#define SYSCLOCK_HW_REG_TCCRXB  TCCR0B
#define SYSCLOCK_HW_REG_TCCRXC  

#define SYSCLOCK_HW_REG_TCNTX   TCNT0
#define SYSCLOCK_HW_REG_TCNTXL  TCNT0
#define SYSCLOCK_HW_REG_TCNTXH   

#define SYSCLOCK_HW_REG_TIMSKX  TIMSK0
#define SYSCLOCK_HW_REG_TIFRX   TIFR0

#define SYSCLOCK_TIMERX_OVF_vect TIMER0_OVF_vect

#elif KERNEL_SYSLOCK_HW_TIMER == 1

#define SYSCLOCK_HW_REG_CSX0    CS10
#define SYSCLOCK_HW_REG_CSX1    CS11
#define SYSCLOCK_HW_REG_CSX2    CS12

#define SYSCLOCK_HW_REG_TCCRXA  TCCR1A
#define SYSCLOCK_HW_REG_TCCRXB  TCCR1B
#define SYSCLOCK_HW_REG_TCCRXC  TCCR1C

#define SYSCLOCK_HW_REG_TCNTX   TCNT1L
#define SYSCLOCK_HW_REG_TCNTXL  TCNT1L
#define SYSCLOCK_HW_REG_TCNTXH  TCNT1H

#define SYSCLOCK_HW_REG_TIMSKX  TIMSK1
#define SYSCLOCK_HW_REG_TIFRX   TIFR1

#define SYSCLOCK_TIMERX_OVF_vect TIMER1_OVF_vect

#elif KERNEL_SYSLOCK_HW_TIMER == 2

#define SYSCLOCK_HW_REG_CSX0    CS20
#define SYSCLOCK_HW_REG_CSX1    CS21
#define SYSCLOCK_HW_REG_CSX2    CS22

#define SYSCLOCK_HW_REG_TCCRXA  TCCR2A
#define SYSCLOCK_HW_REG_TCCRXB  TCCR2B
#define SYSCLOCK_HW_REG_TCCRXC  

#define SYSCLOCK_HW_REG_TCNTX   TCNT2
#define SYSCLOCK_HW_REG_TCNTXL  TCNT2
#define SYSCLOCK_HW_REG_TCNTXH   

#define SYSCLOCK_HW_REG_TIMSKX  TIMSK2
#define SYSCLOCK_HW_REG_TIFRX   TIFR2

#define SYSCLOCK_TIMERX_OVF_vect TIMER2_OVF_vect

#else 
// check if timer is supported
#   error only timer0, timer1 and timer2 are supported for the syslock
#endif

/*___________________________________________________________________________*/

// prescaler
#if KERNEL_SYSLOCK_HW_TIMER == 0 || KERNEL_SYSLOCK_HW_TIMER == 1

#define SYSCLOCK_TIMER_PRESCALER_STOPPED  ((0 << SYSCLOCK_HW_REG_CSX0) | (0 << SYSCLOCK_HW_REG_CSX1) |  (0 << SYSCLOCK_HW_REG_CSX2))
#define SYSCLOCK_TIMER_PRESCALER_1        ((1 << SYSCLOCK_HW_REG_CSX0) | (0 << SYSCLOCK_HW_REG_CSX1) |  (0 << SYSCLOCK_HW_REG_CSX2))
#define SYSCLOCK_TIMER_PRESCALER_8        ((0 << SYSCLOCK_HW_REG_CSX0) | (1 << SYSCLOCK_HW_REG_CSX1) |  (0 << SYSCLOCK_HW_REG_CSX2))
#define SYSCLOCK_TIMER_PRESCALER_64       ((1 << SYSCLOCK_HW_REG_CSX0) | (1 << SYSCLOCK_HW_REG_CSX1) |  (0 << SYSCLOCK_HW_REG_CSX2))
#define SYSCLOCK_TIMER_PRESCALER_256      ((0 << SYSCLOCK_HW_REG_CSX0) | (0 << SYSCLOCK_HW_REG_CSX1) |  (1 << SYSCLOCK_HW_REG_CSX2))
#define SYSCLOCK_TIMER_PRESCALER_1024     ((1 << SYSCLOCK_HW_REG_CSX0) | (0 << SYSCLOCK_HW_REG_CSX1) |  (1 << SYSCLOCK_HW_REG_CSX2))

#elif KERNEL_SYSLOCK_HW_TIMER == 2

#define SYSCLOCK_TIMER_PRESCALER_STOPPED  ((0 << SYSCLOCK_HW_REG_CSX0) | (0 << SYSCLOCK_HW_REG_CSX1) |  (0 << SYSCLOCK_HW_REG_CSX2))
#define SYSCLOCK_TIMER_PRESCALER_1        ((1 << SYSCLOCK_HW_REG_CSX0) | (0 << SYSCLOCK_HW_REG_CSX1) |  (0 << SYSCLOCK_HW_REG_CSX2))
#define SYSCLOCK_TIMER_PRESCALER_8        ((0 << SYSCLOCK_HW_REG_CSX0) | (1 << SYSCLOCK_HW_REG_CSX1) |  (0 << SYSCLOCK_HW_REG_CSX2))
#define SYSCLOCK_TIMER_PRESCALER_32       ((1 << SYSCLOCK_HW_REG_CSX0) | (1 << SYSCLOCK_HW_REG_CSX1) |  (0 << SYSCLOCK_HW_REG_CSX2))
#define SYSCLOCK_TIMER_PRESCALER_64       ((0 << SYSCLOCK_HW_REG_CSX0) | (0 << SYSCLOCK_HW_REG_CSX1) |  (1 << SYSCLOCK_HW_REG_CSX2))
#define SYSCLOCK_TIMER_PRESCALER_128      ((1 << SYSCLOCK_HW_REG_CSX0) | (0 << SYSCLOCK_HW_REG_CSX1) |  (1 << SYSCLOCK_HW_REG_CSX2))
#define SYSCLOCK_TIMER_PRESCALER_256      ((0 << SYSCLOCK_HW_REG_CSX0) | (1 << SYSCLOCK_HW_REG_CSX1) |  (1 << SYSCLOCK_HW_REG_CSX2))
#define SYSCLOCK_TIMER_PRESCALER_1024     ((1 << SYSCLOCK_HW_REG_CSX0) | (1 << SYSCLOCK_HW_REG_CSX1) |  (1 << SYSCLOCK_HW_REG_CSX2))

#endif

/*___________________________________________________________________________*/

// check if time slice is supported
#if KERNEL_DEBUG_PREEMPT_UART == 0
#if KERNEL_SYSLOCK_HW_TIMER == 0 || KERNEL_SYSLOCK_HW_TIMER == 2
#if SYSCLOCK_PERIOD_MS < 1 || SYSCLOCK_PERIOD_MS > 16
#   error unsupported SYSCLOCK_PERIOD_MS for timer 0/2, \
    SYSCLOCK_PERIOD_MS must be in range 1 to 16 (ms)
#endif
#elif KERNEL_SYSLOCK_HW_TIMER == 0
#if SYSCLOCK_PERIOD_MS < 1 || (SYSCLOCK_PERIOD_MS > 16 && (
    SYSCLOCK_PERIOD_MS != 20 &&
    SYSCLOCK_PERIOD_MS != 25 &&
    SYSCLOCK_PERIOD_MS != 50 &&
    SYSCLOCK_PERIOD_MS != 100 &&
    SYSCLOCK_PERIOD_MS != 200 &&
    SYSCLOCK_PERIOD_MS != 250 &&
    SYSCLOCK_PERIOD_MS != 500 &&
    SYSCLOCK_PERIOD_MS != 1000 &&
    SYSCLOCK_PERIOD_MS != 2000 &&
    SYSCLOCK_PERIOD_MS != 2500 &&
    SYSCLOCK_PERIOD_MS != 3000 &&
    SYSCLOCK_PERIOD_MS != 4000 &&
)) 
#   error unsupported SYSCLOCK_PERIOD_MS for timer 1, \
    SYSCLOCK_PERIOD_MS must be in [1; 16] U \
    [20, 25, 50, 100, 200, 250, 500, 1000, 2000, 2500, 3000, 4000]
#endif
#endif
#endif

// timer0
#if KERNEL_SYSLOCK_HW_TIMER == 0
#if SYSCLOCK_PERIOD_MS == 1
#   define KERNEL_SYSCLOCK_TIMER_INTTO  249
#   define SYSCLOCK_TIMER_TCNT   6
#   define SYSCLOCK_TIMER_TCNTL  0x6
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   1000.0
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_64
#elif SYSCLOCK_PERIOD_MS == 2
#   define KERNEL_SYSCLOCK_TIMER_INTTO  124
#   define SYSCLOCK_TIMER_TCNT   131
#   define SYSCLOCK_TIMER_TCNTL  0x83
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   500.0
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_256
#elif SYSCLOCK_PERIOD_MS == 3
#   define KERNEL_SYSCLOCK_TIMER_INTTO  187
#   define SYSCLOCK_TIMER_TCNT   68
#   define SYSCLOCK_TIMER_TCNTL  0x44
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   333.3333333333333
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_256
#elif SYSCLOCK_PERIOD_MS == 4
#   define KERNEL_SYSCLOCK_TIMER_INTTO  249
#   define SYSCLOCK_TIMER_TCNT   6
#   define SYSCLOCK_TIMER_TCNTL  0x6
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   250.0
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_256
#elif SYSCLOCK_PERIOD_MS == 5
#   define KERNEL_SYSCLOCK_TIMER_INTTO  77
#   define SYSCLOCK_TIMER_TCNT   178
#   define SYSCLOCK_TIMER_TCNTL  0xb2
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   200.0
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 6
#   define KERNEL_SYSCLOCK_TIMER_INTTO  93
#   define SYSCLOCK_TIMER_TCNT   162
#   define SYSCLOCK_TIMER_TCNTL  0xa2
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   166.66666666666666
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 7
#   define KERNEL_SYSCLOCK_TIMER_INTTO  108
#   define SYSCLOCK_TIMER_TCNT   147
#   define SYSCLOCK_TIMER_TCNTL  0x93
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   142.85714285714286
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 8
#   define KERNEL_SYSCLOCK_TIMER_INTTO  124
#   define SYSCLOCK_TIMER_TCNT   131
#   define SYSCLOCK_TIMER_TCNTL  0x83
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   125.0
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 9
#   define KERNEL_SYSCLOCK_TIMER_INTTO  140
#   define SYSCLOCK_TIMER_TCNT   115
#   define SYSCLOCK_TIMER_TCNTL  0x73
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   111.11111111111111
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 10
#   define KERNEL_SYSCLOCK_TIMER_INTTO  155
#   define SYSCLOCK_TIMER_TCNT   100
#   define SYSCLOCK_TIMER_TCNTL  0x64
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   100.0
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 11
#   define KERNEL_SYSCLOCK_TIMER_INTTO  171
#   define SYSCLOCK_TIMER_TCNT   84
#   define SYSCLOCK_TIMER_TCNTL  0x54
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   90.90909090909092
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 12
#   define KERNEL_SYSCLOCK_TIMER_INTTO  187
#   define SYSCLOCK_TIMER_TCNT   68
#   define SYSCLOCK_TIMER_TCNTL  0x44
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   83.33333333333333
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 13
#   define KERNEL_SYSCLOCK_TIMER_INTTO  202
#   define SYSCLOCK_TIMER_TCNT   53
#   define SYSCLOCK_TIMER_TCNTL  0x35
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   76.92307692307692
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 14
#   define KERNEL_SYSCLOCK_TIMER_INTTO  218
#   define SYSCLOCK_TIMER_TCNT   37
#   define SYSCLOCK_TIMER_TCNTL  0x25
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   71.42857142857143
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 15
#   define KERNEL_SYSCLOCK_TIMER_INTTO  233
#   define SYSCLOCK_TIMER_TCNT   22
#   define SYSCLOCK_TIMER_TCNTL  0x16
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   66.66666666666667
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 16
#   define KERNEL_SYSCLOCK_TIMER_INTTO  249
#   define SYSCLOCK_TIMER_TCNT   6
#   define SYSCLOCK_TIMER_TCNTL  0x6
#   define SYSCLOCK_TIMER_TCNTH  0x0
#   define SYSCLOCK_TIMER_FREQ   62.5
#   define SYSCLOCK_TIMER_PRESCALER SYSCLOCK_TIMER_PRESCALER_1024
#endif
#endif // timer0

// timer1
#if KERNEL_SYSLOCK_HW_TIMER == 1 
#if SYSCLOCK_PERIOD_MS == 1
#   define SYSCLOCK_TIMER_INTTO        15999
#   define SYSCLOCK_TIMER_TCNT         49536
#   define SYSCLOCK_TIMER_TCNTL        0x80
#   define SYSCLOCK_TIMER_TCNTH        0xc1
#   define SYSCLOCK_TIMER_FREQ         1000.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1
#elif SYSCLOCK_PERIOD_MS == 2
#   define SYSCLOCK_TIMER_INTTO        31999
#   define SYSCLOCK_TIMER_TCNT         33536
#   define SYSCLOCK_TIMER_TCNTL        0x0
#   define SYSCLOCK_TIMER_TCNTH        0x83
#   define SYSCLOCK_TIMER_FREQ         500.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1
#elif SYSCLOCK_PERIOD_MS == 3
#   define SYSCLOCK_TIMER_INTTO        47999
#   define SYSCLOCK_TIMER_TCNT         17536
#   define SYSCLOCK_TIMER_TCNTL        0x80
#   define SYSCLOCK_TIMER_TCNTH        0x44
#   define SYSCLOCK_TIMER_FREQ         333.3333333333333
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1
#elif SYSCLOCK_PERIOD_MS == 4
#   define SYSCLOCK_TIMER_INTTO        63999
#   define SYSCLOCK_TIMER_TCNT         1536
#   define SYSCLOCK_TIMER_TCNTL        0x0
#   define SYSCLOCK_TIMER_TCNTH        0x6
#   define SYSCLOCK_TIMER_FREQ         250.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1
#elif SYSCLOCK_PERIOD_MS == 5
#   define SYSCLOCK_TIMER_INTTO        9999
#   define SYSCLOCK_TIMER_TCNT         55536
#   define SYSCLOCK_TIMER_TCNTL        0xf0
#   define SYSCLOCK_TIMER_TCNTH        0xd8
#   define SYSCLOCK_TIMER_FREQ         200.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_8
#elif SYSCLOCK_PERIOD_MS == 6
#   define SYSCLOCK_TIMER_INTTO        11999
#   define SYSCLOCK_TIMER_TCNT         53536
#   define SYSCLOCK_TIMER_TCNTL        0x20
#   define SYSCLOCK_TIMER_TCNTH        0xd1
#   define SYSCLOCK_TIMER_FREQ         166.66666666666666
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_8
#elif SYSCLOCK_PERIOD_MS == 7
#   define SYSCLOCK_TIMER_INTTO        13999
#   define SYSCLOCK_TIMER_TCNT         51536
#   define SYSCLOCK_TIMER_TCNTL        0x50
#   define SYSCLOCK_TIMER_TCNTH        0xc9
#   define SYSCLOCK_TIMER_FREQ         142.85714285714286
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_8
#elif SYSCLOCK_PERIOD_MS == 8
#   define SYSCLOCK_TIMER_INTTO        15999
#   define SYSCLOCK_TIMER_TCNT         49536
#   define SYSCLOCK_TIMER_TCNTL        0x80
#   define SYSCLOCK_TIMER_TCNTH        0xc1
#   define SYSCLOCK_TIMER_FREQ         125.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_8
#elif SYSCLOCK_PERIOD_MS == 9
#   define SYSCLOCK_TIMER_INTTO        17999
#   define SYSCLOCK_TIMER_TCNT         47536
#   define SYSCLOCK_TIMER_TCNTL        0xb0
#   define SYSCLOCK_TIMER_TCNTH        0xb9
#   define SYSCLOCK_TIMER_FREQ         111.11111111111111
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_8
#elif SYSCLOCK_PERIOD_MS == 10
#   define SYSCLOCK_TIMER_INTTO        19999
#   define SYSCLOCK_TIMER_TCNT         45536
#   define SYSCLOCK_TIMER_TCNTL        0xe0
#   define SYSCLOCK_TIMER_TCNTH        0xb1
#   define SYSCLOCK_TIMER_FREQ         100.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_8
#elif SYSCLOCK_PERIOD_MS == 11
#   define SYSCLOCK_TIMER_INTTO        21999
#   define SYSCLOCK_TIMER_TCNT         43536
#   define SYSCLOCK_TIMER_TCNTL        0x10
#   define SYSCLOCK_TIMER_TCNTH        0xaa
#   define SYSCLOCK_TIMER_FREQ         90.90909090909092
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_8
#elif SYSCLOCK_PERIOD_MS == 12
#   define SYSCLOCK_TIMER_INTTO        23999
#   define SYSCLOCK_TIMER_TCNT         41536
#   define SYSCLOCK_TIMER_TCNTL        0x40
#   define SYSCLOCK_TIMER_TCNTH        0xa2
#   define SYSCLOCK_TIMER_FREQ         83.33333333333333
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_8
#elif SYSCLOCK_PERIOD_MS == 13
#   define SYSCLOCK_TIMER_INTTO        25999
#   define SYSCLOCK_TIMER_TCNT         39536
#   define SYSCLOCK_TIMER_TCNTL        0x70
#   define SYSCLOCK_TIMER_TCNTH        0x9a
#   define SYSCLOCK_TIMER_FREQ         76.92307692307692
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_8
#elif SYSCLOCK_PERIOD_MS == 14
#   define SYSCLOCK_TIMER_INTTO        27999
#   define SYSCLOCK_TIMER_TCNT         37536
#   define SYSCLOCK_TIMER_TCNTL        0xa0
#   define SYSCLOCK_TIMER_TCNTH        0x92
#   define SYSCLOCK_TIMER_FREQ         71.42857142857143
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_8
#elif SYSCLOCK_PERIOD_MS == 15
#   define SYSCLOCK_TIMER_INTTO        29999
#   define SYSCLOCK_TIMER_TCNT         35536
#   define SYSCLOCK_TIMER_TCNTL        0xd0
#   define SYSCLOCK_TIMER_TCNTH        0x8a
#   define SYSCLOCK_TIMER_FREQ         66.66666666666667
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_8
#elif SYSCLOCK_PERIOD_MS == 16
#   define SYSCLOCK_TIMER_INTTO        31999
#   define SYSCLOCK_TIMER_TCNT         33536
#   define SYSCLOCK_TIMER_TCNTL        0x0
#   define SYSCLOCK_TIMER_TCNTH        0x83
#   define SYSCLOCK_TIMER_FREQ         62.5
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_8
#elif SYSCLOCK_PERIOD_MS == 20
#   define SYSCLOCK_TIMER_INTTO        39999
#   define SYSCLOCK_TIMER_TCNT         25536
#   define SYSCLOCK_TIMER_TCNTL        0xc0
#   define SYSCLOCK_TIMER_TCNTH        0x63
#   define SYSCLOCK_TIMER_FREQ         50.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_8
#elif SYSCLOCK_PERIOD_MS == 25
#   define SYSCLOCK_TIMER_INTTO        49999
#   define SYSCLOCK_TIMER_TCNT         15536
#   define SYSCLOCK_TIMER_TCNTL        0xb0
#   define SYSCLOCK_TIMER_TCNTH        0x3c
#   define SYSCLOCK_TIMER_FREQ         40.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_8
#elif SYSCLOCK_PERIOD_MS == 50
#   define SYSCLOCK_TIMER_INTTO        12499
#   define SYSCLOCK_TIMER_TCNT         53036
#   define SYSCLOCK_TIMER_TCNTL        0x2c
#   define SYSCLOCK_TIMER_TCNTH        0xcf
#   define SYSCLOCK_TIMER_FREQ         20.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_64
#elif SYSCLOCK_PERIOD_MS == 100
#   define SYSCLOCK_TIMER_INTTO        24999
#   define SYSCLOCK_TIMER_TCNT         40536
#   define SYSCLOCK_TIMER_TCNTL        0x58
#   define SYSCLOCK_TIMER_TCNTH        0x9e
#   define SYSCLOCK_TIMER_FREQ         10.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_64
#elif SYSCLOCK_PERIOD_MS == 200
#   define SYSCLOCK_TIMER_INTTO        49999
#   define SYSCLOCK_TIMER_TCNT         15536
#   define SYSCLOCK_TIMER_TCNTL        0xb0
#   define SYSCLOCK_TIMER_TCNTH        0x3c
#   define SYSCLOCK_TIMER_FREQ         5.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_64
#elif SYSCLOCK_PERIOD_MS == 250
#   define SYSCLOCK_TIMER_INTTO        62499
#   define SYSCLOCK_TIMER_TCNT         3036
#   define SYSCLOCK_TIMER_TCNTL        0xdc
#   define SYSCLOCK_TIMER_TCNTH        0xb
#   define SYSCLOCK_TIMER_FREQ         4.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_64
#elif SYSCLOCK_PERIOD_MS == 500
#   define SYSCLOCK_TIMER_INTTO        31249
#   define SYSCLOCK_TIMER_TCNT         34286
#   define SYSCLOCK_TIMER_TCNTL        0xee
#   define SYSCLOCK_TIMER_TCNTH        0x85
#   define SYSCLOCK_TIMER_FREQ         2.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_256
#elif SYSCLOCK_PERIOD_MS == 1000
#   define SYSCLOCK_TIMER_INTTO        62499
#   define SYSCLOCK_TIMER_TCNT         3036
#   define SYSCLOCK_TIMER_TCNTL        0xdc
#   define SYSCLOCK_TIMER_TCNTH        0xb
#   define SYSCLOCK_TIMER_FREQ         1.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_256
#elif SYSCLOCK_PERIOD_MS == 2000
#   define SYSCLOCK_TIMER_INTTO        31249
#   define SYSCLOCK_TIMER_TCNT         34286
#   define SYSCLOCK_TIMER_TCNTL        0xee
#   define SYSCLOCK_TIMER_TCNTH        0x85
#   define SYSCLOCK_TIMER_FREQ         0.5
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 2500
#   define SYSCLOCK_TIMER_INTTO        39061
#   define SYSCLOCK_TIMER_TCNT         26474
#   define SYSCLOCK_TIMER_TCNTL        0x6a
#   define SYSCLOCK_TIMER_TCNTH        0x67
#   define SYSCLOCK_TIMER_FREQ         0.4
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 3000
#   define SYSCLOCK_TIMER_INTTO        46874
#   define SYSCLOCK_TIMER_TCNT         18661
#   define SYSCLOCK_TIMER_TCNTL        0xe5
#   define SYSCLOCK_TIMER_TCNTH        0x48
#   define SYSCLOCK_TIMER_FREQ         0.3333333333333333
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 4000
#   define SYSCLOCK_TIMER_INTTO        62499
#   define SYSCLOCK_TIMER_TCNT         3036
#   define SYSCLOCK_TIMER_TCNTL        0xdc
#   define SYSCLOCK_TIMER_TCNTH        0xb
#   define SYSCLOCK_TIMER_FREQ         0.25
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#endif
#endif  // timer1


#if KERNEL_SYSLOCK_HW_TIMER == 2
#if SYSCLOCK_PERIOD_MS == 1
#   define SYSCLOCK_TIMER_INTTO        249
#   define SYSCLOCK_TIMER_TCNT         6
#   define SYSCLOCK_TIMER_TCNTL        0x6
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         1000.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_64
#elif SYSCLOCK_PERIOD_MS == 2
#   define SYSCLOCK_TIMER_INTTO        249
#   define SYSCLOCK_TIMER_TCNT         6
#   define SYSCLOCK_TIMER_TCNTL        0x6
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         500.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_128
#elif SYSCLOCK_PERIOD_MS == 3
#   define SYSCLOCK_TIMER_INTTO        187
#   define SYSCLOCK_TIMER_TCNT         68
#   define SYSCLOCK_TIMER_TCNTL        0x44
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         333.3333333333333
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_256
#elif SYSCLOCK_PERIOD_MS == 4
#   define SYSCLOCK_TIMER_INTTO        249
#   define SYSCLOCK_TIMER_TCNT         6
#   define SYSCLOCK_TIMER_TCNTL        0x6
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         250.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_256
#elif SYSCLOCK_PERIOD_MS == 5
#   define SYSCLOCK_TIMER_INTTO        77
#   define SYSCLOCK_TIMER_TCNT         178
#   define SYSCLOCK_TIMER_TCNTL        0xb2
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         200.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 6
#   define SYSCLOCK_TIMER_INTTO        93
#   define SYSCLOCK_TIMER_TCNT         162
#   define SYSCLOCK_TIMER_TCNTL        0xa2
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         166.66666666666666
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 7
#   define SYSCLOCK_TIMER_INTTO        108
#   define SYSCLOCK_TIMER_TCNT         147
#   define SYSCLOCK_TIMER_TCNTL        0x93
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         142.85714285714286
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 8
#   define SYSCLOCK_TIMER_INTTO        124
#   define SYSCLOCK_TIMER_TCNT         131
#   define SYSCLOCK_TIMER_TCNTL        0x83
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         125.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 9
#   define SYSCLOCK_TIMER_INTTO        140
#   define SYSCLOCK_TIMER_TCNT         115
#   define SYSCLOCK_TIMER_TCNTL        0x73
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         111.11111111111111
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 10
#   define SYSCLOCK_TIMER_INTTO        155
#   define SYSCLOCK_TIMER_TCNT         100
#   define SYSCLOCK_TIMER_TCNTL        0x64
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         100.0
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 11
#   define SYSCLOCK_TIMER_INTTO        171
#   define SYSCLOCK_TIMER_TCNT         84
#   define SYSCLOCK_TIMER_TCNTL        0x54
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         90.90909090909092
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 12
#   define SYSCLOCK_TIMER_INTTO        187
#   define SYSCLOCK_TIMER_TCNT         68
#   define SYSCLOCK_TIMER_TCNTL        0x44
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         83.33333333333333
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 13
#   define SYSCLOCK_TIMER_INTTO        202
#   define SYSCLOCK_TIMER_TCNT         53
#   define SYSCLOCK_TIMER_TCNTL        0x35
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         76.92307692307692
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 14
#   define SYSCLOCK_TIMER_INTTO        218
#   define SYSCLOCK_TIMER_TCNT         37
#   define SYSCLOCK_TIMER_TCNTL        0x25
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         71.42857142857143
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 15
#   define SYSCLOCK_TIMER_INTTO        233
#   define SYSCLOCK_TIMER_TCNT         22
#   define SYSCLOCK_TIMER_TCNTL        0x16
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         66.66666666666667
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#elif SYSCLOCK_PERIOD_MS == 16
#   define SYSCLOCK_TIMER_INTTO        249
#   define SYSCLOCK_TIMER_TCNT         6
#   define SYSCLOCK_TIMER_TCNTL        0x6
#   define SYSCLOCK_TIMER_TCNTH        0x0
#   define SYSCLOCK_TIMER_FREQ         62.5
#   define SYSCLOCK_TIMER_PRESCALER    SYSCLOCK_TIMER_PRESCALER_1024
#endif
#endif 
// timer 2

/*___________________________________________________________________________*/

// registers values

#if KERNEL_SYSLOCK_HW_TIMER == 0

#define SYSCLOCK_HW_VAL_TCCRXA  (0 << COM0A0) | (0 << COM0A1) | (0 << COM0B0) | (0 << COM0B1) | (0 << WGM01) | (0 << WGM00)
#define SYSCLOCK_HW_VAL_TCCRXB  (0 << WGM02) | (0 << FOC0A) | (0 << FOC0B) | SYSCLOCK_TIMER_PRESCALER
#define SYSCLOCK_HW_VAL_TIMSKX  (0 << OCIE0B) | (0 << OCIE0A) | (1 << TOIE0)

#elif KERNEL_SYSLOCK_HW_TIMER == 1

#define SYSCLOCK_HW_VAL_TCCRXA  (0 << COM1A0) | (0 << COM1A1) | (0 << COM1B0) | (0 << COM1B1) | (0 << WGM11) | (0 << WGM10)
#define SYSCLOCK_HW_VAL_TCCRXB  (0 << WGM13) | (0 << WGM12) | (0 << FOC1A) | (0 << FOC1B) | SYSCLOCK_TIMER_PRESCALER
#define SYSCLOCK_HW_VAL_TCCRXC  (0 << FOC1A) | (0 << FOC1B)

#define SYSCLOCK_HW_VAL_TIMSKX  (0 << OCIE1B) | (0 << OCIE1A) | (1 << TOIE1)

#elif KERNEL_SYSLOCK_HW_TIMER == 2

#define SYSCLOCK_HW_VAL_TCCRXA  (0 << COM2A0) | (0 << COM2A1) | (0 << COM2B0) | (0 << COM2B1) | (0 << WGM21) | (0 << WGM20)
#define SYSCLOCK_HW_VAL_TCCRXB  (0 << WGM22) | (0 << FOC2A) | (0 << FOC2B) | SYSCLOCK_TIMER_PRESCALER
#define SYSCLOCK_HW_VAL_TIMSKX  (0 << OCIE2B) | (0 << OCIE2A) | (1 << TOIE2)

#else 
// check if timer is supported
#   error only timer0, timer1 and timer2 are supported for the syslock
#endif

/*___________________________________________________________________________*/

#endif